import { Copy, Pencil, Search, Trash2, Eye } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { Store, StoreSelection, Transaction } from '../types';
import { formatVND } from '../utils/calculations';
import { EmptyState } from '../components/EmptyState';
import { StoreSelector } from '../components/StoreSelector';

export function HistoryPage({ stores, transactions, selection, onSelection, onEdit, onDelete, onClone }: { stores: Store[]; transactions: Transaction[]; selection: StoreSelection; onSelection:(v:StoreSelection)=>void; onEdit:(t:Transaction)=>void; onDelete:(id:string)=>void; onClone:(t:Transaction)=>void }) {
  const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [query,setQuery]=useState(''); const [kind,setKind]=useState<'all'|'purchase'|'sale'|'both'>('all'); const [viewing,setViewing]=useState<Transaction|null>(null);
  const rows = useMemo(()=>transactions.filter(t => (selection==='all'||t.storeId===selection) && (!from||t.date>=from) && (!to||t.date<=to) && (kind==='all'||(kind==='purchase'&&t.purchaseQuantity>0&&t.saleQuantity===0)||(kind==='sale'&&t.saleQuantity>0&&t.purchaseQuantity===0)||(kind==='both'&&t.purchaseQuantity>0&&t.saleQuantity>0)) && (!query||`${t.id} ${t.note||''}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)),[transactions,selection,from,to,query,kind]);
  const name=(id:string)=>stores.find(s=>s.id===id)?.name||id;
  return <div className="space-y-5">
    <StoreSelector stores={stores} value={selection} onChange={onSelection}/>
    <div className="rounded-3xl bg-white p-4 shadow-soft sm:p-5"><div className="grid gap-3 md:grid-cols-5"><label className="text-sm font-semibold text-slate-600">Từ ngày<input type="date" className="field mt-2" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm font-semibold text-slate-600">Đến ngày<input type="date" className="field mt-2" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="text-sm font-semibold text-slate-600">Loại giao dịch<select className="field mt-2" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="all">Tất cả</option><option value="purchase">Chỉ mua</option><option value="sale">Chỉ bán</option><option value="both">Mua & bán</option></select></label><label className="text-sm font-semibold text-slate-600 md:col-span-2">Tìm mã/ghi chú<div className="relative mt-2"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="TG-... hoặc nội dung ghi chú"/></div></label></div></div>
    {rows.length===0?<EmptyState/>:<>
      <div className="space-y-3 lg:hidden">{rows.map(t=><div key={t.id} className="rounded-3xl bg-white p-4 shadow-soft"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-navy">{name(t.storeId)}</p><p className="mt-1 text-xs text-slate-400">{t.date} • {t.id}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${t.profit>=0?'bg-success/10 text-success':'bg-danger/10 text-danger'}`}>{formatVND(t.profit)}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Info label="Mua" value={`${t.purchaseQuantity} • ${formatVND(t.purchaseTotal)}`}/><Info label="Bán" value={`${t.saleQuantity} • ${formatVND(t.saleTotal)}`}/><Info label="Tồn" value={String(t.remainingQuantity)}/><Info label="Ghi chú" value={t.note||'—'}/></div><div className="mt-4 grid grid-cols-4 gap-2"><Action icon={Eye} label="Xem" onClick={()=>setViewing(t)}/><Action icon={Pencil} label="Sửa" onClick={()=>onEdit(t)}/><Action icon={Copy} label="Nhân bản" onClick={()=>onClone(t)}/><Action icon={Trash2} label="Xóa" danger onClick={()=>onDelete(t.id)}/></div></div>)}</div>
      <div className="hidden overflow-x-auto rounded-3xl bg-white shadow-soft lg:block"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-navy text-white"><tr>{['Ngày','Cửa hàng','SL mua','Giá mua','Tiền mua','SL bán','Giá bán','Tiền bán','Lợi nhuận','Tồn','Thao tác'].map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{rows.map(t=><tr key={t.id} className="border-b border-slate-100"><td className="px-4 py-3">{t.date}</td><td className="px-4 py-3 font-semibold">{name(t.storeId)}</td><td className="px-4 py-3">{t.purchaseQuantity}</td><td className="px-4 py-3">{formatVND(t.purchaseUnitPrice)}</td><td className="px-4 py-3">{formatVND(t.purchaseTotal)}</td><td className="px-4 py-3">{t.saleQuantity}</td><td className="px-4 py-3">{formatVND(t.saleUnitPrice)}</td><td className="px-4 py-3">{formatVND(t.saleTotal)}</td><td className="px-4 py-3 font-bold text-success">{formatVND(t.profit)}</td><td className="px-4 py-3">{t.remainingQuantity}</td><td className="px-4 py-3"><div className="flex gap-1"><Action icon={Eye} label="Xem" onClick={()=>setViewing(t)}/><Action icon={Pencil} label="Sửa" onClick={()=>onEdit(t)}/><Action icon={Copy} label="Nhân bản" onClick={()=>onClone(t)}/><Action icon={Trash2} label="Xóa" danger onClick={()=>onDelete(t.id)}/></div></td></tr>)}</tbody></table></div>
    </>}
    {viewing&&<div className="fixed inset-0 z-[90] grid place-items-end bg-black/35 p-3 sm:place-items-center" onClick={()=>setViewing(null)}><div className="w-full max-w-lg rounded-[28px] bg-white p-5" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-champagne">CHI TIẾT GIAO DỊCH</p><h3 className="mt-1 font-bold text-navy">{viewing.id}</h3></div><button className="btn-secondary !w-auto" onClick={()=>setViewing(null)}>Đóng</button></div><div className="mt-5 grid grid-cols-2 gap-3"><Info label="Ngày" value={viewing.date}/><Info label="Cửa hàng" value={name(viewing.storeId)}/><Info label="Tiền mua" value={formatVND(viewing.purchaseTotal)}/><Info label="Tiền bán" value={formatVND(viewing.saleTotal)}/><Info label="Lợi nhuận" value={formatVND(viewing.profit)}/><Info label="Tồn" value={String(viewing.remainingQuantity)}/></div><p className="mt-4 rounded-2xl bg-appgray p-4 text-sm text-slate-600">{viewing.note||'Không có ghi chú.'}</p></div></div>}
  </div>;
}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 break-words font-semibold text-navy">{value}</p></div>}
function Action({icon:Icon,label,onClick,danger=false}:{icon:any;label:string;onClick:()=>void;danger?:boolean}){return <button aria-label={label} title={label} onClick={onClick} className={`grid min-h-10 min-w-10 place-items-center rounded-xl ${danger?'bg-danger/10 text-danger':'bg-appgray text-navy'} active:scale-95`}><Icon size={17}/></button>}
