import { Download, FileJson, HelpCircle, RotateCcw, Save, Trash2, Upload } from 'lucide-react';
import { useRef, useState } from 'react';
import type { AppSettings, Store, StoreSelection, Transaction } from '../types';
import { StoreSelector } from '../components/StoreSelector';
import { exportBackup, importBackup } from '../utils/storage';
import { sampleTransactions } from '../data/sampleData';

export function SettingsPage({stores,settings,transactions,selection,onSelection,onStores,onSettings,onTransactions,onClear,onGuide,onToast}:{stores:Store[];settings:AppSettings;transactions:Transaction[];selection:StoreSelection;onSelection:(v:StoreSelection)=>void;onStores:(s:Store[])=>void;onSettings:(s:AppSettings)=>void;onTransactions:(t:Transaction[])=>void;onClear:()=>void;onGuide:()=>void;onToast:(m:string)=>void}){
  const [draft,setDraft]=useState(stores); const fileRef=useRef<HTMLInputElement>(null);
  const save=()=>{onStores(draft.map(s=>({...s,updatedAt:new Date().toISOString()})));onToast('Đã cập nhật thông tin cửa hàng');};
  const downloadBackup=()=>{const blob=new Blob([exportBackup(transactions,stores,settings)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`TravisGold_Backup_${new Date().toLocaleDateString('sv-SE')}.json`;a.click();URL.revokeObjectURL(url);onToast('Đã xuất file sao lưu JSON');};
  const importFile=async(file?:File)=>{if(!file)return;try{const data=importBackup(await file.text());onTransactions(data.transactions);onStores(data.stores);onSettings(data.settings);setDraft(data.stores);onToast('Khôi phục dữ liệu thành công');}catch(e){alert(e instanceof Error?e.message:'Không thể đọc file.')}};
  const clear=()=>{if(!confirm('Xác nhận lần 1: Xóa toàn bộ dữ liệu TravisGold trên thiết bị này?'))return;if(!confirm('Xác nhận lần 2: Dữ liệu không thể khôi phục nếu chưa sao lưu. Tiếp tục?'))return;onClear();setDraft(stores);};
  const toggleSample=()=>{const next=!settings.sampleEnabled;onSettings({...settings,sampleEnabled:next});const sampleIds=new Set(sampleTransactions.map(t=>t.id));if(next){const existing=new Set(transactions.map(t=>t.id));onTransactions([...sampleTransactions.filter(t=>!existing.has(t.id)),...transactions]);}else{onTransactions(transactions.filter(t=>!sampleIds.has(t.id)));}onToast(next?'Đã bật dữ liệu mẫu':'Đã tắt và gỡ dữ liệu mẫu');};
  return <div className="space-y-5"><StoreSelector stores={stores} value={selection} onChange={onSelection}/>
    <section className="rounded-3xl bg-white p-5 shadow-soft"><h2 className="text-lg font-bold text-navy">Cửa hàng</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{draft.map((s,i)=><div key={s.id} className="rounded-2xl bg-appgray p-4"><label className="text-sm font-semibold text-slate-600">Tên cửa hàng {i+1}<input className="field mt-2" value={s.name} onChange={e=>setDraft(draft.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/></label><label className="mt-4 block text-sm font-semibold text-slate-600">Màu nhận diện<div className="mt-2 flex items-center gap-3"><input aria-label={`Màu ${s.name}`} type="color" value={s.color} onChange={e=>setDraft(draft.map(x=>x.id===s.id?{...x,color:e.target.value}:x))} className="h-11 w-16 rounded-xl border-0 bg-transparent"/><span className="font-mono text-xs text-slate-500">{s.color}</span></div></label></div>)}</div><button onClick={save} className="btn-primary mt-4 w-full sm:w-auto"><Save size={18}/>Lưu tên & màu</button></section>
    <section className="rounded-3xl bg-white p-5 shadow-soft"><h2 className="text-lg font-bold text-navy">Dữ liệu & sao lưu</h2><p className="mt-2 text-sm leading-6 text-slate-500">Dữ liệu hiện chỉ lưu trên thiết bị này. Safari ở iPhone khác sẽ có bộ dữ liệu độc lập nếu chưa khôi phục từ JSON.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><button onClick={downloadBackup} className="btn-secondary"><Download size={18}/>Xuất sao lưu JSON</button><button onClick={()=>fileRef.current?.click()} className="btn-secondary"><Upload size={18}/>Nhập dữ liệu JSON</button><input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={e=>importFile(e.target.files?.[0])}/><button onClick={toggleSample} className="btn-secondary"><FileJson size={18}/>{settings.sampleEnabled?'Tắt':'Bật'} dữ liệu mẫu</button><button onClick={onGuide} className="btn-secondary"><HelpCircle size={18}/>Hướng dẫn cài PWA</button></div><button onClick={clear} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-2xl border border-danger/20 bg-danger/10 px-4 font-semibold text-danger"><Trash2 size={18}/>Xóa toàn bộ dữ liệu</button></section>
    <section className="rounded-3xl bg-white p-5 shadow-soft"><h2 className="text-lg font-bold text-navy">Ứng dụng</h2><div className="mt-4 flex items-center justify-between border-b border-slate-100 py-3 text-sm"><span className="text-slate-500">Tiền tệ</span><b>VND (₫)</b></div><div className="flex items-center justify-between py-3 text-sm"><span className="text-slate-500">Phiên bản</span><b>{settings.version}</b></div></section>
  </div>
}
